name: Scrape Prices

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.8

      - run: poetry install
      - run: python3 scrape.py

      - id: get-date
        run: echo "::set-output name=value::$(date --iso-8601)"

      - name: commit all changed/added files in data/
        uses: EndBug/add-and-commit@v7
        with:
          add: 'data'
          default_author: github_actions
          message: "bot: update data for ${{ steps.get-date.outputs.value }}"
